### ISSUE TITLE
add css for blockquotes

### ISSUE THREAD

**Issue by aaronpk** [cleverdevil/together#39]
In addition to indentation, I like when blockquotes have a left border. I know it's totally a personal preference thing but I think it helps. I believe github does it as well:

> test quote

Here's a mockup of some quick css i added in the browser: 

![blockquote](https://media.aaronpk.com/Screen-Shot-2018-02-18-09-51-53-8cgYQU3eA6.jpg)

```css
blockquote {
    border-left: 4px #dfe2e5 solid;
    padding-left: 1em;
}
```
