### ISSUE TITLE
Crash when in-reply-to contains name, url, and type

### ISSUE THREAD

**Issue by jackjamieson2** [cleverdevil/together#80]
I'm adjusting Yarns' parsing code (incorporating @dshanske's updates to  wordpress-post-kinds' parse-this) and am experiencing some crashes. I think I've narrowed it down and I'm not sure if it might be a bug on my end or in Together.

When in-reply-to contains an array with name, url, and type Together crashes upon previewing a feed. 
e.g. a post on tantek.com contains: 

```
in-reply-to:
  name: "aaronparecki.com’s post"
  url: "https://aaronparecki.com/2018/09/07/1/"
  type: "cite"
```

The error console links to 
https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bname%2C%20url%2C%20type%7D&args[]=

When I adjust the response to just have a URL it seems to work fine
`in-reply-to: "https://aaronparecki.com/2018/09/07/1/"`

Do you have any thoughts about whether this is something that should be addressed within Together or whether it is an error on my server side?
